 source 'https://rubygems.org'

gem 'middleman'
# gem 'middleman-syntax'
# gem 'middleman-autoprefixer'
# gem 'middleman-sprockets'
# gem 'redcarpet', '~> 3.2.3'
# gem 'rouge', '~> 2.0.5'
# # gem 'sassc'
# # gem 'sassc-rails'
# gem 'sprockets'
# gem 'uglifier', '>= 1.3.0'

gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-sprockets', '~> 4.1.0'
gem 'nokogiri', '~> 1.8.2'
gem 'normalize-scss'
gem 'normalize-rails'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'sprockets', github: 'rails/sprockets'
gem 'therubyracer'

